app_id: "bcf7c952-15e9-4794-8ce7-8869332ddd8d"
app_secret: "dyqOGT53-;abjjENLW771|)"
redirect: "http://localhost:8000/callback"
scopes: "openid profile offline_access user.read user.readwrite.all calendars.read sites.read.all Sites.ReadWrite.All"
authority: "https://login.microsoftonline.com/common"
authorize_endpoint: "/oauth2/v2.0/authorize"
token_endpoint: "/oauth2/v2.0/token"
